export const farmsdata = [
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: true,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: true,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },
    {
        title: "Brush-Chad",
        first: "brush",
        second: "chad",
        apy: 2000.0,
        approved: false,
        earn: "Chad",
        earned: 0,
        staked: 0,
        fee: 0,
        liquidity: 1000000,
        multiplier: 50
    },



]